#! /bin/csh -f
set INCLUDE = /Users/zhengwei/workspace_c/lib
set CSLIB = $INCLUDE/cslib.a
set LIBRARIES = ($CSLIB -lm)
foreach x ($*)
  if ("x$x" == "x-c") then
    set LIBRARIES = ""
    break
  endif
end
gcc -g -I$INCLUDE $* $LIBRARIES
